spring.application.name=placement-system

# Database Configuration (PostgreSQL / H2 dynamically configured)
spring.datasource.url=jdbc:postgresql://localhost:5432/ffdb
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=postgres
spring.datasource.password=REALME08
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

spring.h2.console.enabled=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
jwt.secret=${JWT_SECRET:9a67471b48ee4797a70007916c18894f7965004e0e4f454a8523c923f06d9b6a}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Google Auth
google.client.id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}

# Load local API keys (this file is ignored by Git)
spring.config.import=optional:file:application-secrets.properties

# AWS S3 Cloud Storage Config
aws.access.key=${AWS_ACCESS_KEY:YOUR_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY:YOUR_SECRET_KEY}
aws.s3.bucket=${AWS_S3_BUCKET:placement-system-resumes}
aws.s3.region=${AWS_S3_REGION:us-east-1}

# Allow large file uploads (PDF resumes up to 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


